mysql_root_password: "{{ vault_mysql_root_password }}" # Define this variable in group_vars/production/vault.yml

ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@139.6.141.9 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa"'
